build: false

os: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - MINICONDA: C:\xeus-conda

init:
  - "ECHO %MINICONDA%"
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\xeus-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  # Install conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install cmake cppzmq=4.3.0 zeromq=4.2.5 xtl=0.5 nlohmann_json=3.4.0 cryptopp=7.0.0 -c conda-forge
  - conda install pytest jupyter jupyter_kernel_test=0.3.0 -c conda-forge
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -D CMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -D BUILD_EXAMPLES=ON -D DOWNLOAD_GTEST=ON -Dgtest_force_shared_crt=ON ..
  - nmake

build_script:
  - .\test\test_xeus
  - py.test test\test_echo_kernel.py
